"""Markdown content cleaning: removes scraping artifacts to improve LLM signal/noise ratio."""

import re

# ---------------------------------------------------------------------------
# Cloudflare / JS email-protection obfuscation artifacts
# ---------------------------------------------------------------------------
# Cloudflare renders protected addresses as text containing a non-breaking
# space (U+00A0) between "email" and "protected", e.g. "[email\u00a0protected]".
# After markdownify the pattern may also appear with a literal HTML entity.
_CF_EMAIL_RE = re.compile(
    r"\[(?:email|mail|e-mail)\s*(?:\u00a0|&#160;|&#xa0;)?protected\]",
    re.IGNORECASE,
)

# Generic encoded/obfuscated phone/email patterns sometimes left by JS scrapers
# e.g. "tel:+1%20555%20123%204567" or entities like "&#43;" scattered in text
_ENCODED_PHONE_RE = re.compile(r"tel:[^\s\)\"'>]+", re.IGNORECASE)
_HTML_ENTITY_NOISE_RE = re.compile(r"&#\d{1,5};")

# ---------------------------------------------------------------------------
# Cookie-consent / GDPR pop-up residual text
# ---------------------------------------------------------------------------
_COOKIE_PATTERNS = [
    re.compile(
        r"(?i)this\s+(?:website|site)\s+uses?\s+cookies[^.]*\.",
    ),
    re.compile(
        r"(?i)we\s+use\s+cookies[^.]*\.",
    ),
    re.compile(
        r"(?i)by\s+(?:using|clicking|browsing|continuing)[^,\.]*"
        r"[,\.]\s*you\s+(?:agree|accept|consent)[^.]*\.",
    ),
    re.compile(r"(?i)(?:accept|reject|decline)\s+(?:all\s+)?cookies[^.]*\."),
    re.compile(r"(?i)cookie\s+(?:policy|preferences|settings|consent|notice)[^.]*\."),
    re.compile(r"(?i)manage\s+(?:cookie|privacy)\s+settings[^.]*\."),
    re.compile(r"(?i)privacy\s+policy\s*[|·•\-–]\s*cookie\s+policy"),
]

# ---------------------------------------------------------------------------
# Structural noise
# ---------------------------------------------------------------------------
# Three or more consecutive blank lines → normalise to two
_MULTI_BLANK_LINE_RE = re.compile(r"\n{3,}")

# Lone asterisks / underscores / hyphens on their own line (horizontal-rule
# noise sometimes generated by markdownify from empty <hr> or stray <br>)
_STRAY_DIVIDER_RE = re.compile(r"^[ \t]*[-*_]{1,3}[ \t]*$", re.MULTILINE)

# Markdown link whose display text is empty or only whitespace: [  ](url)
_EMPTY_LINK_RE = re.compile(r"\[\s*\]\([^)]*\)")


def clean_markdown(text: str) -> str:
    """Remove common scraping artifacts from *text* (Markdown string).

    Operations applied in order:

    1. Remove Cloudflare email-protection placeholders.
    2. Remove residual ``tel:`` URI noise.
    3. Remove stray HTML numeric entities (e.g. ``&#160;``).
    4. Remove typical cookie-consent / GDPR pop-up sentences.
    5. Remove empty Markdown links.
    6. Remove stray single-character divider lines.
    7. Collapse three or more consecutive blank lines into two.
    8. Strip leading/trailing whitespace.
    """
    if not text:
        return text

    text = _CF_EMAIL_RE.sub("", text)
    text = _ENCODED_PHONE_RE.sub("", text)
    text = _HTML_ENTITY_NOISE_RE.sub("", text)

    for pattern in _COOKIE_PATTERNS:
        text = pattern.sub("", text)

    text = _EMPTY_LINK_RE.sub("", text)
    text = _STRAY_DIVIDER_RE.sub("", text)
    text = _MULTI_BLANK_LINE_RE.sub("\n\n", text)

    return text.strip()
